package vistas.Directivo;

import Controlador.GestorBD;
import Model.Salas;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class abmSala extends javax.swing.JFrame {

    GestorBD g = new GestorBD();
    private static final String PASS = "123";
    private static final String USER = "sa";
    private static final String CADENA = "jdbc:sqlserver://DESKTOP-ANUONV0:1433;databaseName=KASprueba";
    principalDirectivo pdi;
    int idSalaModificar = 0;

    public abmSala() {
        initComponents();
        actualizarTabla();
        Desactivar();
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));

        return logo;
    }

    public void actualizarTabla() {
        DefaultTableModel tmodel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<Salas> list = g.getSalas();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tmodel.setColumnIdentifiers(new Object[]{"NroSala", "Nombre", "Turno", "Hora de Entrada", "Hora de Salida"});
        for (Salas salas : list) {
            tmodel.addRow(new Object[]{salas.getIdSala(), salas.getDescripcion(), salas.getTurno(), salas.getHoraEntrada(), salas.getHoraSalida()});
        }
        tblRegAula.setModel(tmodel);
        tblRegAula.getTableHeader().setReorderingAllowed(false);
        tblRegAula.getTableHeader().setBackground(new Color(153, 255, 153));
        tblRegAula.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 12));
        tblRegAula.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblRegAula.getColumnModel().getColumn(0).setMaxWidth(0);
        tblRegAula.getColumnModel().getColumn(0).setMinWidth(0);
        tblRegAula.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblRegAula.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblRegAula.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblRegAula.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tblRegAula.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSala = new org.edisoncor.gui.panel.Panel();
        pnl2Sala = new org.edisoncor.gui.panel.Panel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblRegDocente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegAula = new javax.swing.JTable();
        btnNuevoAula = new org.edisoncor.gui.button.ButtonColoredAction();
        btnUpdateAula = new org.edisoncor.gui.button.ButtonColoredAction();
        btnDeleteAula = new org.edisoncor.gui.button.ButtonColoredAction();
        btnGuardarModAula = new org.edisoncor.gui.button.ButtonColoredAction();
        btnInsertAula = new org.edisoncor.gui.button.ButtonColoredAction();
        lblDescripcion = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        txtTurno = new org.edisoncor.gui.textField.TextField();
        txtNombreSala = new org.edisoncor.gui.textField.TextField();
        txtHoraEntrada = new org.edisoncor.gui.textField.TextField();
        txtHoraSalida = new org.edisoncor.gui.textField.TextField();
        lblHoraSalida = new javax.swing.JLabel();
        lblHoraEntrada = new javax.swing.JLabel();
        btnCronograma = new org.edisoncor.gui.button.ButtonColoredAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - REGISTRO DE SALAS");
        setIconImage(getIconImage());
        setName("frmSala"); // NOI18N
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlSala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otroFondo2.jpg"))); // NOI18N

        pnl2Sala.setBackground(new java.awt.Color(0, 0, 0));
        pnl2Sala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnl2Sala.setColorPrimario(new java.awt.Color(0, 0, 0));

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimo.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblRegDocente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblRegDocente.setForeground(new java.awt.Color(255, 255, 255));
        lblRegDocente.setText(" REGISTRO DE SALAS");

        javax.swing.GroupLayout pnl2SalaLayout = new javax.swing.GroupLayout(pnl2Sala);
        pnl2Sala.setLayout(pnl2SalaLayout);
        pnl2SalaLayout.setHorizontalGroup(
            pnl2SalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2SalaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        pnl2SalaLayout.setVerticalGroup(
            pnl2SalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblRegDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl2SalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblRegAula.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblRegAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegAulaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRegAula);

        btnNuevoAula.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevoAula.setBorder(null);
        btnNuevoAula.setText("NUEVO");
        btnNuevoAula.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnNuevoAula.setDireccionDeSombra(0);
        btnNuevoAula.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnNuevoAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoAula.setProfundidad(new java.lang.Float(0.0F));
        btnNuevoAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAulaActionPerformed(evt);
            }
        });

        btnUpdateAula.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdateAula.setBorder(null);
        btnUpdateAula.setText("MODIFICAR");
        btnUpdateAula.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnUpdateAula.setDireccionDeSombra(0);
        btnUpdateAula.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnUpdateAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateAula.setProfundidad(new java.lang.Float(0.0F));
        btnUpdateAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAulaActionPerformed(evt);
            }
        });

        btnDeleteAula.setBackground(new java.awt.Color(51, 51, 51));
        btnDeleteAula.setBorder(null);
        btnDeleteAula.setText("ELIMINAR");
        btnDeleteAula.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnDeleteAula.setDireccionDeSombra(0);
        btnDeleteAula.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnDeleteAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteAula.setProfundidad(new java.lang.Float(0.0F));
        btnDeleteAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAulaActionPerformed(evt);
            }
        });

        btnGuardarModAula.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardarModAula.setBorder(null);
        btnGuardarModAula.setText("GUARDAR");
        btnGuardarModAula.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnGuardarModAula.setDireccionDeSombra(0);
        btnGuardarModAula.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardarModAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarModAula.setProfundidad(new java.lang.Float(0.0F));
        btnGuardarModAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModAulaActionPerformed(evt);
            }
        });

        btnInsertAula.setBackground(new java.awt.Color(51, 51, 51));
        btnInsertAula.setBorder(null);
        btnInsertAula.setText("AGREGAR");
        btnInsertAula.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnInsertAula.setDireccionDeSombra(0);
        btnInsertAula.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnInsertAula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertAula.setProfundidad(new java.lang.Float(0.0F));
        btnInsertAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertAulaActionPerformed(evt);
            }
        });

        lblDescripcion.setBackground(new java.awt.Color(0, 102, 0));
        lblDescripcion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(153, 255, 153));
        lblDescripcion.setText("Nombre: ");
        lblDescripcion.setOpaque(true);

        lblTurno.setBackground(new java.awt.Color(0, 102, 0));
        lblTurno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblTurno.setForeground(new java.awt.Color(153, 255, 153));
        lblTurno.setText("Turno: ");
        lblTurno.setOpaque(true);

        txtTurno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        txtNombreSala.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        txtHoraEntrada.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        txtHoraSalida.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        lblHoraSalida.setBackground(new java.awt.Color(0, 102, 0));
        lblHoraSalida.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblHoraSalida.setForeground(new java.awt.Color(153, 255, 153));
        lblHoraSalida.setText("Horario de Salida:");
        lblHoraSalida.setOpaque(true);

        lblHoraEntrada.setBackground(new java.awt.Color(0, 102, 0));
        lblHoraEntrada.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblHoraEntrada.setForeground(new java.awt.Color(153, 255, 153));
        lblHoraEntrada.setText("Horario de Entrada: ");
        lblHoraEntrada.setOpaque(true);

        btnCronograma.setBackground(new java.awt.Color(51, 51, 51));
        btnCronograma.setBorder(null);
        btnCronograma.setText("VER CRONOGRAMA DE SALA");
        btnCronograma.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnCronograma.setDireccionDeSombra(5);
        btnCronograma.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnCronograma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCronogramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalaLayout = new javax.swing.GroupLayout(pnlSala);
        pnlSala.setLayout(pnlSalaLayout);
        pnlSalaLayout.setHorizontalGroup(
            pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2Sala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSalaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSalaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalaLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lblTurno)
                                    .addComponent(lblHoraEntrada)
                                    .addComponent(lblHoraSalida)
                                    .addComponent(lblDescripcion)
                                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlSalaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnGuardarModAula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnInsertAula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlSalaLayout.createSequentialGroup()
                        .addComponent(btnNuevoAula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateAula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlSalaLayout.setVerticalGroup(
            pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalaLayout.createSequentialGroup()
                .addComponent(pnl2Sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSalaLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHoraEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHoraSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarModAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la ventana?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void tblRegAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegAulaMouseClicked
        btnUpdateAula.setEnabled(true);
        btnInsertAula.setEnabled(false);
        btnDeleteAula.setEnabled(true);
        btnNuevoAula.setEnabled(false);
        btnGuardarModAula.setEnabled(false);
    }//GEN-LAST:event_tblRegAulaMouseClicked

    private void btnNuevoAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAulaActionPerformed
        activarNuevo();
        limpiar();
    }//GEN-LAST:event_btnNuevoAulaActionPerformed

    private void btnUpdateAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAulaActionPerformed
        idSalaModificar = (int) tblRegAula.getValueAt(tblRegAula.getSelectedRow(), 0);
        ArrayList<Salas> list = g.getSalas();
        for (Salas x : list) {
            if (x.getIdSala() == idSalaModificar) {
                txtNombreSala.setText(x.getDescripcion());
                txtTurno.setText(x.getTurno());
                txtHoraEntrada.setText(x.getHoraEntrada() + "");
                txtHoraSalida.setText(x.getHoraSalida() + "");
            }
        }
        txtNombreSala.setEnabled(true);
        txtTurno.setEnabled(true);
        txtHoraSalida.setEnabled(true);
        txtHoraEntrada.setEnabled(true);
        btnGuardarModAula.setEnabled(true);
        btnDeleteAula.setEnabled(true);
    }//GEN-LAST:event_btnUpdateAulaActionPerformed

    private void btnDeleteAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAulaActionPerformed
        try {
            int idSalaDelete = (int) tblRegAula.getValueAt(tblRegAula.getSelectedRow(), 0);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar esta sala?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
            if (respuesta == 0) {
                g.EliminarSala(idSalaDelete);
            }
            actualizarTabla();
            JOptionPane.showMessageDialog(null, "Registro eliminado con éxito");
        } catch (Exception e) {
            System.out.println("Error metodo eliminar SALA ");
        }
    }//GEN-LAST:event_btnDeleteAulaActionPerformed

    private void btnGuardarModAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModAulaActionPerformed
        String descripcion = txtNombreSala.getText();
        String turno = txtTurno.getText();
        String horaEntrada = txtHoraEntrada.getText();
        String horaSalida = txtHoraSalida.getText();

        Salas s = new Salas(idSalaModificar,descripcion, turno, horaEntrada, horaSalida);

        g.ModificarSala(s);
        actualizarTabla();
        limpiar();
        btnUpdateAula.setEnabled(false);
        btnInsertAula.setEnabled(false);
        btnDeleteAula.setEnabled(true);
        btnNuevoAula.setEnabled(true);
        btnGuardarModAula.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Guardado con exito");
    }//GEN-LAST:event_btnGuardarModAulaActionPerformed

    private void btnInsertAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertAulaActionPerformed
        try {
            Connection conexion = DriverManager.getConnection(CADENA, USER, PASS);
            PreparedStatement ps = conexion.prepareStatement("insert into Salas values(?,?,?,?)");
            if (txtNombreSala.getText().trim() == null || txtTurno.getText().trim().isEmpty() || txtHoraEntrada.getText().trim().equals("") || txtHoraSalida.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Falta ingresar datos, revise por favor");
            } else {
                ps.setString(1, txtNombreSala.getText());
                ps.setString(2, txtTurno.getText());
                ps.setString(3, txtHoraEntrada.getText());
                ps.setString(4, txtHoraSalida.getText());

                ps.execute();

                ps.close();
                actualizarTabla();
                limpiar();
                Desactivar();
                JOptionPane.showMessageDialog(null, "Cargado con exito");
            }
            conexion.close();
        } catch (Exception ex) {
            System.out.println("Error metodo AGREGAR SALA " + ex);
        }
    }//GEN-LAST:event_btnInsertAulaActionPerformed

    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCronogramaActionPerformed
        idSalaModificar = (int) tblRegAula.getValueAt(tblRegAula.getSelectedRow(), 0);
        ArrayList<Salas> listaS = g.getSalas();
        for (Salas salas : listaS) {
            if (salas.getIdSala() == idSalaModificar) {
                if ("Mañana".equalsIgnoreCase(salas.getTurno())) {
                    ListaHorariosMañana lhm = new ListaHorariosMañana();
                    lhm.setVisible(true);
                    lhm.actualizarPanel(idSalaModificar);
                } else {
                    ListaHorariosTarde lht = new ListaHorariosTarde();
                    lht.setVisible(true);
                    lht.actualizarPanel(idSalaModificar);
                }
            }
        }
    }//GEN-LAST:event_btnCronogramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abmSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abmSala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private org.edisoncor.gui.button.ButtonColoredAction btnCronograma;
    private org.edisoncor.gui.button.ButtonColoredAction btnDeleteAula;
    private org.edisoncor.gui.button.ButtonColoredAction btnGuardarModAula;
    private org.edisoncor.gui.button.ButtonColoredAction btnInsertAula;
    private javax.swing.JButton btnMinimizar;
    private org.edisoncor.gui.button.ButtonColoredAction btnNuevoAula;
    private org.edisoncor.gui.button.ButtonColoredAction btnUpdateAula;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblRegDocente;
    private javax.swing.JLabel lblTurno;
    private org.edisoncor.gui.panel.Panel pnl2Sala;
    private org.edisoncor.gui.panel.Panel pnlSala;
    private javax.swing.JTable tblRegAula;
    private org.edisoncor.gui.textField.TextField txtHoraEntrada;
    private org.edisoncor.gui.textField.TextField txtHoraSalida;
    private org.edisoncor.gui.textField.TextField txtNombreSala;
    private org.edisoncor.gui.textField.TextField txtTurno;
    // End of variables declaration//GEN-END:variables

    private void activarNuevo() {
        txtNombreSala.setEnabled(true);
        txtTurno.setEnabled(true);
        txtHoraEntrada.setEnabled(true);
        txtHoraSalida.setEnabled(true);
        btnInsertAula.setEnabled(true);
        btnDeleteAula.setEnabled(false);
        btnUpdateAula.setEnabled(false);
        btnNuevoAula.setEnabled(false);
        btnGuardarModAula.setEnabled(false);
    }

    private void limpiar() {
        txtNombreSala.setText("");
        txtTurno.setText("");
        txtHoraEntrada.setText("");
        txtHoraSalida.setText("");
    }

    private void Desactivar() {

        txtNombreSala.setEnabled(false);
        txtTurno.setEnabled(false);
        txtHoraEntrada.setEnabled(false);
        txtHoraSalida.setEnabled(false);
        btnInsertAula.setEnabled(false);
        btnGuardarModAula.setEnabled(false);
        btnUpdateAula.setEnabled(false);
        btnDeleteAula.setEnabled(false);
        btnNuevoAula.setEnabled(true);

    }
}
