package vistas.Directivo;

import Controlador.GestorBD;
import Model.TiposLogins;
import Model.Usuarios;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class abmUsuario extends javax.swing.JFrame {

    GestorBD g = new GestorBD();
    private static final String PASS = "123";
    private static final String USER = "sa";
    private static final String CADENA = "jdbc:sqlserver://DESKTOP-ANUONV0:1433;databaseName=KASprueba";
    principalDirectivo pdi;
    DefaultComboBoxModel cboModelTipoLogin = new DefaultComboBoxModel();
    ArrayList<TiposLogins> listLog = g.getTiposLogins();
    int idUserModificar = 0;

    public abmUsuario() {
        initComponents();
        actualizarTabla();
        Desactivar();
        for (TiposLogins tiposLogins : listLog) {
            cboModelTipoLogin.addElement(tiposLogins.getDescripcion());
        }
        cboTipoLogin.setModel(cboModelTipoLogin);
        Desactivar();
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));
        return logo;
    }

    public void actualizarTabla() {
        DefaultTableModel tmodel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<Usuarios> list = g.getUsuarios();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        tmodel.setColumnIdentifiers(new Object[]{"Id Usuario", "Usuarios", "Tipo de Perfil",});
        for (Usuarios usuarios : list) {
            tmodel.addRow(new Object[]{usuarios.getIdLogin(), usuarios.getUsuario(), usuarios.getDescripcion()});
            tmodel.isCellEditable(1, 1);
        }
        tblRegUser.setModel(tmodel);
        tblRegUser.getTableHeader().setReorderingAllowed(false);
        tblRegUser.getTableHeader().setBackground(new Color(153, 255, 153));
        tblRegUser.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 12));
        tblRegUser.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblRegUser.getColumnModel().getColumn(0).setMaxWidth(0);
        tblRegUser.getColumnModel().getColumn(0).setMinWidth(0);
        tblRegUser.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblRegUser.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblRegUser.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new org.edisoncor.gui.panel.Panel();
        pnlUser = new org.edisoncor.gui.panel.Panel();
        lblRegDocente = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnNuevoUser = new org.edisoncor.gui.button.ButtonColoredAction();
        btnUpdateUser = new org.edisoncor.gui.button.ButtonColoredAction();
        btnDeleteUser = new org.edisoncor.gui.button.ButtonColoredAction();
        btnGuardarModUser = new org.edisoncor.gui.button.ButtonColoredAction();
        btnInsertUser = new org.edisoncor.gui.button.ButtonColoredAction();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegUser = new javax.swing.JTable();
        cboTipoLogin = new javax.swing.JComboBox<>();
        lblTipoUser = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new org.edisoncor.gui.textField.TextField();
        txtClave = new org.edisoncor.gui.textField.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - USUARIOS");
        setIconImage(getIconImage());
        setName("frmUsuarios"); // NOI18N
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otroFondo2.jpg"))); // NOI18N

        pnlUser.setBackground(new java.awt.Color(0, 0, 0));
        pnlUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlUser.setColorPrimario(new java.awt.Color(0, 0, 0));
        pnlUser.setName(""); // NOI18N

        lblRegDocente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRegDocente.setForeground(new java.awt.Color(255, 255, 255));
        lblRegDocente.setText("REGISTRO DE USUARIOS");

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimo.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMinimizar)
                    .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblRegDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnNuevoUser.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevoUser.setBorder(null);
        btnNuevoUser.setText("NUEVO");
        btnNuevoUser.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnNuevoUser.setDireccionDeSombra(0);
        btnNuevoUser.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnNuevoUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoUser.setProfundidad(new java.lang.Float(0.0F));
        btnNuevoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdateUser.setBorder(null);
        btnUpdateUser.setText("MODIFICAR");
        btnUpdateUser.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnUpdateUser.setDireccionDeSombra(0);
        btnUpdateUser.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnUpdateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateUser.setProfundidad(new java.lang.Float(0.0F));
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(51, 51, 51));
        btnDeleteUser.setBorder(null);
        btnDeleteUser.setText("ELIMINAR");
        btnDeleteUser.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnDeleteUser.setDireccionDeSombra(0);
        btnDeleteUser.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteUser.setProfundidad(new java.lang.Float(0.0F));
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnGuardarModUser.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardarModUser.setBorder(null);
        btnGuardarModUser.setText("GUARDAR");
        btnGuardarModUser.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnGuardarModUser.setDireccionDeSombra(0);
        btnGuardarModUser.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnGuardarModUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarModUser.setProfundidad(new java.lang.Float(0.0F));
        btnGuardarModUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModUserActionPerformed(evt);
            }
        });

        btnInsertUser.setBackground(new java.awt.Color(51, 51, 51));
        btnInsertUser.setBorder(null);
        btnInsertUser.setText("AGREGAR");
        btnInsertUser.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnInsertUser.setDireccionDeSombra(0);
        btnInsertUser.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnInsertUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertUser.setProfundidad(new java.lang.Float(0.0F));
        btnInsertUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUserActionPerformed(evt);
            }
        });

        tblRegUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tblRegUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRegUser);

        cboTipoLogin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cboTipoLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboTipoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoLoginActionPerformed(evt);
            }
        });

        lblTipoUser.setBackground(new java.awt.Color(0, 102, 0));
        lblTipoUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblTipoUser.setForeground(new java.awt.Color(153, 255, 153));
        lblTipoUser.setText("Tipo de Perfil:");
        lblTipoUser.setOpaque(true);

        lblClave.setBackground(new java.awt.Color(0, 102, 0));
        lblClave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblClave.setForeground(new java.awt.Color(153, 255, 153));
        lblClave.setText("Clave: ");
        lblClave.setOpaque(true);

        lblUser.setBackground(new java.awt.Color(0, 102, 0));
        lblUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(153, 255, 153));
        lblUser.setText("Usuario: ");
        lblUser.setOpaque(true);

        txtUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        txtClave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(120, 120, 120))
                            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cboTipoLogin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(lblTipoUser)
                                .addGap(151, 151, 151))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(lblClave)
                                .addGap(173, 173, 173))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(lblUser)
                                .addGap(170, 170, 170))))))
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnGuardarModUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 69, Short.MAX_VALUE))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblClave, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cboTipoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarModUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la ventana?", "Selecione un Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnNuevoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUserActionPerformed
        activarNuevo();
        limpiar();
    }//GEN-LAST:event_btnNuevoUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        idUserModificar = (int) tblRegUser.getValueAt(tblRegUser.getSelectedRow(), 0);
        ArrayList<Usuarios> list = g.getUsuarios();
        for (Usuarios x : list) {
            if (x.getIdLogin() == idUserModificar) {
                txtUser.setText(x.getUsuario());
                txtClave.setText(x.getClave());
                for (TiposLogins tiposLogins : listLog) {
                    if (tiposLogins.getIdTipoLogin() == x.getIdTipoLogin()) {
                        cboTipoLogin.setSelectedItem(tiposLogins.getDescripcion());
                    }
                }
            }
        }
        txtUser.setEnabled(true);
        txtClave.setEnabled(true);
        cboTipoLogin.setEnabled(true);
        btnGuardarModUser.setEnabled(true);
        btnDeleteUser.setEnabled(false);
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        try {
            int idUserDelete = (int) tblRegUser.getValueAt(tblRegUser.getSelectedRow(), 0);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea elimnar el usuario?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
            if (respuesta == 0) {
                g.EliminarUsuario(idUserDelete);
            }
            actualizarTabla();
            Desactivar();
            JOptionPane.showMessageDialog(null, "Registro eliminado con éxito");
        } catch (Exception e) {
            System.out.println("Error metodo eliminar USUARIO s");
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnGuardarModUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModUserActionPerformed
        String usuario = txtUser.getText();
        String clave = txtClave.getText();
        int idTipoLogin = 0;
        for (TiposLogins tiposLogins : listLog) {
            if (tiposLogins.getDescripcion().equals(cboTipoLogin.getSelectedItem())) {
                idTipoLogin = (tiposLogins.getIdTipoLogin());
            }
        }

        Usuarios u = new Usuarios(usuario, clave, idTipoLogin, idUserModificar);

        g.ModificarUsuario(u);
        actualizarTabla();
        limpiar();
        btnUpdateUser.setEnabled(false);
        btnInsertUser.setEnabled(false);
        btnDeleteUser.setEnabled(false);
        btnNuevoUser.setEnabled(true);
        btnGuardarModUser.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Guardado con exito");
    }//GEN-LAST:event_btnGuardarModUserActionPerformed

    private void btnInsertUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUserActionPerformed
        try {
            Connection conexion = DriverManager.getConnection(CADENA, USER, PASS);
            PreparedStatement ps = conexion.prepareStatement("insert into Usuarios values (?,?,?)");
            if (txtUser.getText().trim().equals("") || txtClave.getText().trim().equals("") || cboTipoLogin.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Faltan datos de cargar");
            }else{
            ps.setString(1, txtUser.getText());
            ps.setString(2, txtClave.getText());
            for (TiposLogins tiposLogins : listLog) {
                if (tiposLogins.getDescripcion().equals(cboTipoLogin.getSelectedItem())) {
                    ps.setInt(3, tiposLogins.getIdTipoLogin());
                }
            }
            ps.execute();

            ps.close();
            limpiar();
            Desactivar();
            JOptionPane.showMessageDialog(null, "Cargado con exito");
            }
            conexion.close();
            actualizarTabla();
        } catch (Exception ex) {
            System.out.println("Error metodo AGREGAR USUARIO " + ex);
        }
    }//GEN-LAST:event_btnInsertUserActionPerformed

    private void tblRegUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegUserMouseClicked
        btnUpdateUser.setEnabled(true);
        btnInsertUser.setEnabled(false);
        btnDeleteUser.setEnabled(true);
        btnNuevoUser.setEnabled(false);
        btnGuardarModUser.setEnabled(false);
    }//GEN-LAST:event_tblRegUserMouseClicked

    private void cboTipoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private org.edisoncor.gui.button.ButtonColoredAction btnDeleteUser;
    private org.edisoncor.gui.button.ButtonColoredAction btnGuardarModUser;
    private org.edisoncor.gui.button.ButtonColoredAction btnInsertUser;
    private javax.swing.JButton btnMinimizar;
    private org.edisoncor.gui.button.ButtonColoredAction btnNuevoUser;
    private org.edisoncor.gui.button.ButtonColoredAction btnUpdateUser;
    private javax.swing.JComboBox<String> cboTipoLogin;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblRegDocente;
    private javax.swing.JLabel lblTipoUser;
    private javax.swing.JLabel lblUser;
    private org.edisoncor.gui.panel.Panel pnlUser;
    private org.edisoncor.gui.panel.Panel pnlUsuario;
    private javax.swing.JTable tblRegUser;
    private org.edisoncor.gui.textField.TextField txtClave;
    private org.edisoncor.gui.textField.TextField txtUser;
    // End of variables declaration//GEN-END:variables
    private void activarNuevo() {
        txtUser.setEnabled(true);
        txtClave.setEnabled(true);
        cboTipoLogin.setSelectedIndex(0);
        cboTipoLogin.setEnabled(true);
        btnInsertUser.setEnabled(true);
        btnDeleteUser.setEnabled(false);
        btnUpdateUser.setEnabled(false);
        btnNuevoUser.setEnabled(false);
        btnGuardarModUser.setEnabled(false);
    }

    private void limpiar() {
        txtUser.setText("");
        txtClave.setText("");
        cboTipoLogin.setSelectedIndex(-1);

    }

    private void Desactivar() {
        txtUser.setEnabled(false);
        txtClave.setEnabled(false);
        cboTipoLogin.setSelectedIndex(-1);
        cboTipoLogin.setEnabled(false);
        btnInsertUser.setEnabled(false);
        btnGuardarModUser.setEnabled(false);
        btnUpdateUser.setEnabled(false);
        btnDeleteUser.setEnabled(false);
        btnNuevoUser.setEnabled(true);
    }
}
