package vistas.Directivo;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import vistas.Docente.abmEstudiante;
import vistas.Docente.abmFamilia;
import vistas.Docente.abmTutor;
import vistas.Inicio.inicioSesion;

public class principalDirectivo extends javax.swing.JFrame {

    public principalDirectivo() {
        initComponents();
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));
        return logo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDirectivos = new org.edisoncor.gui.panel.Panel();
        pnl2Directivos = new org.edisoncor.gui.panel.Panel();
        btnCerrar = new javax.swing.JButton();
        lblDirectivos = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnDireDoc = new javax.swing.JButton();
        btnDireEmple = new javax.swing.JButton();
        btnDireUsers = new javax.swing.JButton();
        btnDireSalas = new javax.swing.JButton();
        btnFamilia = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCronograma = new javax.swing.JButton();
        lblPresione = new javax.swing.JLabel();
        btnCobros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - DIRECTIVOS");
        setIconImage(getIconImage());
        setName("frmDirectivo"); // NOI18N
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlDirectivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlDirectivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLoogin.jpg"))); // NOI18N

        pnl2Directivos.setBackground(new java.awt.Color(0, 0, 0));
        pnl2Directivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnl2Directivos.setColorPrimario(new java.awt.Color(0, 0, 0));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblDirectivos.setBackground(new java.awt.Color(0, 0, 0));
        lblDirectivos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDirectivos.setForeground(new java.awt.Color(255, 255, 255));
        lblDirectivos.setText("DIRECTIVOS");
        lblDirectivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimo.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2DirectivosLayout = new javax.swing.GroupLayout(pnl2Directivos);
        pnl2Directivos.setLayout(pnl2DirectivosLayout);
        pnl2DirectivosLayout.setHorizontalGroup(
            pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2DirectivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDirectivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl2DirectivosLayout.setVerticalGroup(
            pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDirectivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMinimizar)
                .addComponent(btnCerrar))
        );

        btnDireDoc.setBackground(new java.awt.Color(245, 245, 220));
        btnDireDoc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDireDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/docentes.png"))); // NOI18N
        btnDireDoc.setText("Docentes");
        btnDireDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDireDoc.setContentAreaFilled(false);
        btnDireDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDireDoc.setIconTextGap(0);
        btnDireDoc.setOpaque(true);
        btnDireDoc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDireDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDireDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireDocActionPerformed(evt);
            }
        });

        btnDireEmple.setBackground(new java.awt.Color(245, 245, 220));
        btnDireEmple.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDireEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conference-call.png"))); // NOI18N
        btnDireEmple.setText("Empleadas/os");
        btnDireEmple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDireEmple.setContentAreaFilled(false);
        btnDireEmple.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDireEmple.setIconTextGap(0);
        btnDireEmple.setOpaque(true);
        btnDireEmple.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDireEmple.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDireEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireEmpleActionPerformed(evt);
            }
        });

        btnDireUsers.setBackground(new java.awt.Color(245, 245, 220));
        btnDireUsers.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDireUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/users.png"))); // NOI18N
        btnDireUsers.setText("Usuarios");
        btnDireUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDireUsers.setContentAreaFilled(false);
        btnDireUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDireUsers.setIconTextGap(0);
        btnDireUsers.setOpaque(true);
        btnDireUsers.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDireUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDireUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireUsersActionPerformed(evt);
            }
        });

        btnDireSalas.setBackground(new java.awt.Color(245, 245, 220));
        btnDireSalas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnDireSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door1.png"))); // NOI18N
        btnDireSalas.setText("Salas");
        btnDireSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDireSalas.setContentAreaFilled(false);
        btnDireSalas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDireSalas.setIconTextGap(0);
        btnDireSalas.setOpaque(true);
        btnDireSalas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDireSalas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDireSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireSalasActionPerformed(evt);
            }
        });

        btnFamilia.setBackground(new java.awt.Color(245, 245, 220));
        btnFamilia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tutores.jpg"))); // NOI18N
        btnFamilia.setText("Familia");
        btnFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFamilia.setContentAreaFilled(false);
        btnFamilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFamilia.setIconTextGap(0);
        btnFamilia.setOpaque(true);
        btnFamilia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFamilia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliaActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(245, 245, 220));
        btnReportes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReportes.setContentAreaFilled(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setIconTextGap(0);
        btnReportes.setOpaque(true);
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnCronograma.setBackground(new java.awt.Color(245, 245, 220));
        btnCronograma.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cronograma.png"))); // NOI18N
        btnCronograma.setText("Cronograma");
        btnCronograma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCronograma.setContentAreaFilled(false);
        btnCronograma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCronograma.setIconTextGap(0);
        btnCronograma.setOpaque(true);
        btnCronograma.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCronograma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCronogramaActionPerformed(evt);
            }
        });

        lblPresione.setBackground(new java.awt.Color(245, 245, 220));
        lblPresione.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPresione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresione.setText("PRESIONE UNA OPCIÓN: ");
        lblPresione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        lblPresione.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPresione.setOpaque(true);

        btnCobros.setBackground(new java.awt.Color(245, 245, 220));
        btnCobros.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCobros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pay.png"))); // NOI18N
        btnCobros.setText("Cobros");
        btnCobros.setAlignmentY(0.0F);
        btnCobros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCobros.setContentAreaFilled(false);
        btnCobros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCobros.setIconTextGap(0);
        btnCobros.setOpaque(true);
        btnCobros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCobros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDirectivosLayout = new javax.swing.GroupLayout(pnlDirectivos);
        pnlDirectivos.setLayout(pnlDirectivosLayout);
        pnlDirectivosLayout.setHorizontalGroup(
            pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2Directivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDirectivosLayout.createSequentialGroup()
                .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDirectivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPresione))
                    .addGroup(pnlDirectivosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDireSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDireDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDireEmple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCronograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDireUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCobros, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlDirectivosLayout.setVerticalGroup(
            pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDirectivosLayout.createSequentialGroup()
                .addComponent(pnl2Directivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblPresione, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDireDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDireEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDireUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDireSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCobros, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlDirectivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDirectivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir de KAS?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
            inicioSesion is = new inicioSesion();
            is.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnDireSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireSalasActionPerformed
        abmSala abmS = new abmSala();
        abmS.setVisible(true);
    }//GEN-LAST:event_btnDireSalasActionPerformed

    private void btnDireDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireDocActionPerformed
        abmDocente abmD = new abmDocente();
        abmD.setVisible(true);
    }//GEN-LAST:event_btnDireDocActionPerformed

    private void btnDireUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireUsersActionPerformed
        abmUsuario abmU = new abmUsuario();
        abmU.setVisible(true);
    }//GEN-LAST:event_btnDireUsersActionPerformed

    private void btnDireEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireEmpleActionPerformed
        abmEmpleado abmEm = new abmEmpleado();
        abmEm.setVisible(true);
    }//GEN-LAST:event_btnDireEmpleActionPerformed
    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();    }//GEN-LAST:event_formMousePressed

    private void btnFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliaActionPerformed
        abmFamilia abmF = new abmFamilia();
        abmF.interfazDirectivo(this);
        abmF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFamiliaActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Reportes r = new Reportes();
        r.interfazDirectivo(this);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCronogramaActionPerformed
        abmCronograma c = new abmCronograma();
        c.setVisible(true);                
    }//GEN-LAST:event_btnCronogramaActionPerformed

    private void btnCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrosActionPerformed
       abmCobros ac = new abmCobros();
       ac.setVisible(true);
    }//GEN-LAST:event_btnCobrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalDirectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalDirectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalDirectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalDirectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalDirectivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCobros;
    private javax.swing.JButton btnCronograma;
    private javax.swing.JButton btnDireDoc;
    private javax.swing.JButton btnDireEmple;
    private javax.swing.JButton btnDireSalas;
    private javax.swing.JButton btnDireUsers;
    private javax.swing.JButton btnFamilia;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel lblDirectivos;
    private javax.swing.JLabel lblPresione;
    private org.edisoncor.gui.panel.Panel pnl2Directivos;
    private org.edisoncor.gui.panel.Panel pnlDirectivos;
    // End of variables declaration//GEN-END:variables
}
