package vistas.Directivo;

import Controlador.GestorBD;
import Model.Salas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import vistas.Docente.principalDocente;
import vistas.Otro.principalOtro;

public class Reportes extends javax.swing.JFrame {

    GestorBD g = new GestorBD();
    private static final String PASS = "123";
    private static final String USER = "sa";
    private static final String CADENA = "jdbc:sqlserver://DESKTOP-ANUONV0:1433;databaseName=KASprueba";
    principalDocente pd;
    principalDirectivo pdi;
    principalOtro pa;
    String ventana = "";
    ArrayList<Salas> listaSalas = g.getSalas();

    public Reportes() {
        initComponents();

        for (Salas x : listaSalas) {
            cboSalas.addItem(x.getDescripcion());
            System.out.println(x.getDescripcion());
        }
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));
        return logo;
    }

    public void interfazDocente(principalDocente pdc) {
        pd = pdc;
        ventana = "docente";
    }

    public void interfazDirectivo(principalDirectivo pdir) {
        pdi = pdir;
        ventana = "directivo";
    }

    public void interfazAdmin(principalOtro pa) {
        pa = pa;
        ventana = "admin";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        pnl2Directivos = new org.edisoncor.gui.panel.Panel();
        btnCerrar = new javax.swing.JButton();
        lblDirectivos = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        lblPresione = new javax.swing.JLabel();
        lblNumeroSala = new javax.swing.JLabel();
        lblFecNac = new javax.swing.JLabel();
        btnListadoFecNac = new javax.swing.JButton();
        txtReporteEstu = new org.edisoncor.gui.textField.TextField();
        btnListadoSala1 = new javax.swing.JButton();
        cboSalas = new javax.swing.JComboBox<>();
        lblNumeroSala1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - REPORTES");
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otroFondo2.jpg"))); // NOI18N

        pnl2Directivos.setBackground(new java.awt.Color(0, 0, 0));
        pnl2Directivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnl2Directivos.setColorPrimario(new java.awt.Color(0, 0, 0));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblDirectivos.setBackground(new java.awt.Color(0, 0, 0));
        lblDirectivos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDirectivos.setForeground(new java.awt.Color(255, 255, 255));
        lblDirectivos.setText("REPORTES");
        lblDirectivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimo.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2DirectivosLayout = new javax.swing.GroupLayout(pnl2Directivos);
        pnl2Directivos.setLayout(pnl2DirectivosLayout);
        pnl2DirectivosLayout.setHorizontalGroup(
            pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2DirectivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDirectivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl2DirectivosLayout.setVerticalGroup(
            pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDirectivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2DirectivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnMinimizar)
                .addComponent(btnCerrar))
        );

        lblPresione.setBackground(new java.awt.Color(204, 204, 204));
        lblPresione.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPresione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresione.setText("PRESIONE UNA OPCIÓN: ");
        lblPresione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        lblPresione.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPresione.setOpaque(true);

        lblNumeroSala.setBackground(new java.awt.Color(204, 204, 204));
        lblNumeroSala.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblNumeroSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroSala.setText("Generar listado de alumnos de una sala");
        lblNumeroSala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNumeroSala.setOpaque(true);

        lblFecNac.setBackground(new java.awt.Color(204, 204, 204));
        lblFecNac.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblFecNac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecNac.setText(" Ingresar Año de la Fecha de Nac:");
        lblFecNac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFecNac.setOpaque(true);

        btnListadoFecNac.setText("Generar Listado");
        btnListadoFecNac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListadoFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoFecNacActionPerformed(evt);
            }
        });

        txtReporteEstu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        btnListadoSala1.setText("Generar Listado");
        btnListadoSala1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListadoSala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoSala1ActionPerformed(evt);
            }
        });

        cboSalas.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cboSalas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cboSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSalasActionPerformed(evt);
            }
        });

        lblNumeroSala1.setBackground(new java.awt.Color(204, 204, 204));
        lblNumeroSala1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblNumeroSala1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroSala1.setText("Sala");
        lblNumeroSala1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNumeroSala1.setOpaque(true);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2Directivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblPresione, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(391, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumeroSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSalas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumeroSala1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReporteEstu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListadoFecNac)
                            .addComponent(btnListadoSala1))
                        .addGap(73, 73, 73))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(pnl2Directivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPresione, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addComponent(lblNumeroSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblNumeroSala, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addComponent(btnListadoSala1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporteEstu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la ventana?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            if ("docente".equals(ventana)) {
                pd.setVisible(true);
            } else {
                if ("directivo".equals(ventana)) {
                    pdi.setVisible(true);
                } else {
                    pa.setVisible(true);
                    this.dispose();
                }
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnListadoFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoFecNacActionPerformed
      try {
            Connection conexion = DriverManager.getConnection(CADENA, USER, PASS);
            int año = Integer.parseInt(txtReporteEstu.getText());
            JasperReport archivo;
            archivo = JasperCompileManager.compileReport("reports/ListaEstudiante.jrxml");
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("año", año);
            map.put("IconReport", "Imagenes/icons8-business-report-64.png");
            JasperPrint prin = JasperFillManager.fillReport(archivo, map, conexion);
            if (prin.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay alumnos que nacieron en este año");
            } else {
                JOptionPane.showMessageDialog(null, "Reporte generado");
                JasperViewer ver = new JasperViewer(prin, false);
                ver.setVisible(true);
                ver.setLocationRelativeTo(null);
            }
        } catch (JRException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListadoFecNacActionPerformed

    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnListadoSala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoSala1ActionPerformed
        String nombreSala = cboSalas.getSelectedItem().toString();
        int idSala = 0;
        for (Salas x : listaSalas) {
            if (x.getDescripcion().equalsIgnoreCase(nombreSala)) {
                idSala = x.getIdSala();
            }
        }
        try {
            Connection conexion = DriverManager.getConnection(CADENA, USER, PASS);
            JasperReport archivo;
            archivo = JasperCompileManager.compileReport("reports/ListaSala.jrxml");
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("pIdSala", idSala);
            map.put("IconReport", "Imagenes/icons8-business-report-64.png");
            JasperPrint prin = JasperFillManager.fillReport(archivo, map, conexion);
            if (prin.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La sala no contiene alumnos");
            } else {
                JOptionPane.showMessageDialog(null, "Reporte generado");

                JasperViewer ver = new JasperViewer(prin, false);

                ver.setVisible(true);
                ver.setLocationRelativeTo(null);
            }
        } catch (JRException | SQLException ex) {
        }
    }//GEN-LAST:event_btnListadoSala1ActionPerformed

    private void cboSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSalasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnListadoFecNac;
    private javax.swing.JButton btnListadoSala1;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JComboBox<String> cboSalas;
    private javax.swing.JLabel lblDirectivos;
    private javax.swing.JLabel lblFecNac;
    private javax.swing.JLabel lblNumeroSala;
    private javax.swing.JLabel lblNumeroSala1;
    private javax.swing.JLabel lblPresione;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel pnl2Directivos;
    private org.edisoncor.gui.textField.TextField txtReporteEstu;
    // End of variables declaration//GEN-END:variables
}
