package vistas.Inicio;

import Controlador.GestorBD;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vistas.Directivo.principalDirectivo;
import vistas.Docente.principalDocente;
import vistas.Otro.principalOtro;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

public class inicioSesion extends javax.swing.JFrame {

    GestorBD g = new GestorBD();

    public inicioSesion() {
        initComponents();
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));
        return logo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        pnlInicioSesion = new org.edisoncor.gui.panel.Panel();
        lblHdInicioSesion = new org.edisoncor.gui.label.LabelHeader();
        txtUsuario = new org.edisoncor.gui.textField.TextField();
        pswClave = new org.edisoncor.gui.passwordField.PasswordField();
        lblClave = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        rbtDirectivos = new javax.swing.JRadioButton();
        rbtDocentes = new javax.swing.JRadioButton();
        rbtOtro = new javax.swing.JRadioButton();
        btnAceptar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - INICIO SESIÓN");
        setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        setIconImage(getIconImage());
        setName("frmInicioSesion"); // NOI18N
        setUndecorated(true);

        pnlInicioSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLoogin.jpg"))); // NOI18N
        pnlInicioSesion.setMaximumSize(new java.awt.Dimension(400, 300));
        pnlInicioSesion.setPreferredSize(new java.awt.Dimension(700, 400));

        lblHdInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        lblHdInicioSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHdInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHdInicioSesion.setText("INICIO DE SESIÓN");
        lblHdInicioSesion.setColor(new java.awt.Color(51, 51, 51));
        lblHdInicioSesion.setColorDeSombra(new java.awt.Color(51, 51, 51));
        lblHdInicioSesion.setColored(true);
        lblHdInicioSesion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        pswClave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        lblClave.setBackground(new java.awt.Color(0, 0, 0));
        lblClave.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lblClave.setText("CLAVE DE ACCESO : ");

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lblUsuario.setText("USUARIO : ");

        lblPerfil.setBackground(new java.awt.Color(0, 0, 0));
        lblPerfil.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lblPerfil.setText("ELIJA SU PERFIL : ");

        btnGroup.add(rbtDirectivos);
        rbtDirectivos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtDirectivos.setText("Directivos");
        rbtDirectivos.setContentAreaFilled(false);

        btnGroup.add(rbtDocentes);
        rbtDocentes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtDocentes.setText("Docentes");
        rbtDocentes.setContentAreaFilled(false);

        btnGroup.add(rbtOtro);
        rbtOtro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rbtOtro.setText("Otros");
        rbtOtro.setContentAreaFilled(false);
        rbtOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtOtroActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(51, 51, 51));
        btnAceptar.setBorder(null);
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnAceptar.setDireccionDeSombra(0);
        btnAceptar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setProfundidad(new java.lang.Float(0.0F));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setBorder(null);
        btnCancelar.setText("CANCELAR");
        btnCancelar.setColorDeSombra(new java.awt.Color(51, 51, 51));
        btnCancelar.setDireccionDeSombra(0);
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setProfundidad(new java.lang.Float(0.0F));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        clockDigital1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlInicioSesionLayout = new javax.swing.GroupLayout(pnlInicioSesion);
        pnlInicioSesion.setLayout(pnlInicioSesionLayout);
        pnlInicioSesionLayout.setHorizontalGroup(
            pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHdInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(pnlInicioSesionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlInicioSesionLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPerfil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rbtOtro)
                        .addComponent(rbtDocentes)
                        .addComponent(rbtDirectivos)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pswClave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInicioSesionLayout.setVerticalGroup(
            pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInicioSesionLayout.createSequentialGroup()
                .addComponent(lblHdInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave)
                    .addComponent(pswClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfil)
                    .addComponent(rbtDirectivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtDocentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtOtro)
                .addGap(18, 18, 18)
                .addGroup(pnlInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir de KAS?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
            System.exit(1);
        } else {
            Limpiar();
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbtOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtOtroActionPerformed

    }//GEN-LAST:event_rbtOtroActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (validar()) {
            try {
                String usuario = txtUsuario.getText();
                String password = String.copyValueOf(pswClave.getPassword());

                int tipoLogin = 0;
                if (rbtDirectivos.isSelected()) {
                    tipoLogin = 1;

                } else {
                    if (rbtDocentes.isSelected()) {
                        tipoLogin = 2;
                    } else {
                        if (rbtOtro.isSelected()) {
                            tipoLogin = 3;
                        }
                    }
                }
                if (g.existeUsuario(usuario, password, tipoLogin) == true) {
                    if (rbtDirectivos.isSelected()) {
                        principalDirectivo pd = new principalDirectivo();
                        pd.setVisible(true);
                    } else {
                        if (rbtDocentes.isSelected()) {
                            principalDocente pdc = new principalDocente();
                            pdc.setVisible(true);
                        } else {
                            if (rbtOtro.isSelected()) {
                                principalOtro po = new principalOtro();
                                po.setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Debe marcar un Perfil");
                            }
                        }
                    }
                this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos. Vuelva a ingresar.");
                    Limpiar();
                }

            } catch (Exception ex) {
                System.out.println("Metodo inicio de sesion MAL " + ex);
            }

        }


    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonColoredAction btnAceptar;
    private org.edisoncor.gui.button.ButtonColoredAction btnCancelar;
    private javax.swing.ButtonGroup btnGroup;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JLabel lblClave;
    private org.edisoncor.gui.label.LabelHeader lblHdInicioSesion;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblUsuario;
    private org.edisoncor.gui.panel.Panel pnlInicioSesion;
    private org.edisoncor.gui.passwordField.PasswordField pswClave;
    private javax.swing.JRadioButton rbtDirectivos;
    private javax.swing.JRadioButton rbtDocentes;
    private javax.swing.JRadioButton rbtOtro;
    private org.edisoncor.gui.textField.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        if (txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar un Usuario");
            return false;
        }
        if (pswClave.getPassword().length > 1) {
        } else {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una Contraseña");
            return false;
        }
        if (!rbtDirectivos.isSelected()) {
            if (!rbtDocentes.isSelected()) {
                if (!rbtOtro.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Debe Seleccionar una opcion");
                    return false;
                }
            }
        }

        return true;
    }

    private void Limpiar() {

        txtUsuario.setText("");
        pswClave.setText("");
        btnGroup.clearSelection();
        rbtDirectivos.setSelected(false);
        rbtDocentes.setSelected(false);
        rbtOtro.setSelected(false);

    }
}
