package vistas.Inicio;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.scene.control.ProgressBar;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;
import javax.swing.Timer;

public class Principal extends javax.swing.JFrame {

    private Timer tiempo;
    int cont = -1;
    public final static int TWO_SECOND = 3;

    public Principal() {
        initComponents();
        tiempo = new Timer(TWO_SECOND, new TimerListener());
        tiempo.start();
    }
    
         public Image getIconImage() 
    {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));

        return logo;
    }
    
    public void cerrarPrincipal(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new org.edisoncor.gui.panel.Panel();
        pbrPrincipal = new org.edisoncor.gui.progressBar.ProgressBarRect();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - PRINCIPAL");
        setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        setIconImage(getIconImage());
        setName("frmPrincipal"); // NOI18N
        setUndecorated(true);

        pnlPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Diapositiva1.JPG"))); // NOI18N

        pbrPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pbrPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        pbrPrincipal.setBorde(0.0F);
        pbrPrincipal.setBorderPainted(false);
        pbrPrincipal.setColorDeBorde(new java.awt.Color(204, 204, 204));
        pbrPrincipal.setColorDeSombra(new java.awt.Color(255, 102, 51));
        pbrPrincipal.setColorDeTexto(new java.awt.Color(255, 102, 51));
        pbrPrincipal.setDistanciaDeSombra(30);
        pbrPrincipal.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        pbrPrincipal.setStringPainted(true);
        pbrPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pbrPrincipalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbrPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 350, Short.MAX_VALUE)
                .addComponent(pbrPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void pbrPrincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pbrPrincipalKeyTyped

    }//GEN-LAST:event_pbrPrincipalKeyTyped

    public class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent ae) {
            cont++;
            pbrPrincipal.setValue(cont);
            if (cont == 100) {
                tiempo.stop();
                inicioSesion is = new inicioSesion();
                is.setVisible(true);
                cerrarPrincipal();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.progressBar.ProgressBarRect pbrPrincipal;
    private org.edisoncor.gui.panel.Panel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
