package vistas.Docente;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import vistas.Directivo.Reportes;
import vistas.Directivo.abmSala;
import vistas.Inicio.inicioSesion;

public class principalDocente extends javax.swing.JFrame {

    public principalDocente() {
        initComponents();
    }

    public Image getIconImage() {
        Image logo = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/DIAPOSITIVA1.jpg"));

        return logo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrinDocente = new org.edisoncor.gui.panel.Panel();
        pnl2PrinDocente = new org.edisoncor.gui.panel.Panel();
        lblDocente = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnAulas = new javax.swing.JButton();
        lblPresioneOpcion = new javax.swing.JLabel();
        btnFamilias = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAS - DOCENTES");
        setIconImage(getIconImage());
        setName("frmPrincDocente"); // NOI18N
        setUndecorated(true);

        pnlPrinDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        pnlPrinDocente.setColorPrimario(new java.awt.Color(255, 153, 0));
        pnlPrinDocente.setColorSecundario(new java.awt.Color(255, 255, 102));
        pnlPrinDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoLoogin.jpg"))); // NOI18N
        pnlPrinDocente.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pnlPrinDocenteInputMethodTextChanged(evt);
            }
        });

        pnl2PrinDocente.setBackground(new java.awt.Color(0, 0, 0));
        pnl2PrinDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnl2PrinDocente.setColorPrimario(new java.awt.Color(0, 0, 0));

        lblDocente.setBackground(new java.awt.Color(0, 0, 0));
        lblDocente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDocente.setForeground(new java.awt.Color(255, 255, 255));
        lblDocente.setText("DOCENTES");

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimo.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl2PrinDocenteLayout = new javax.swing.GroupLayout(pnl2PrinDocente);
        pnl2PrinDocente.setLayout(pnl2PrinDocenteLayout);
        pnl2PrinDocenteLayout.setHorizontalGroup(
            pnl2PrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2PrinDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl2PrinDocenteLayout.setVerticalGroup(
            pnl2PrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2PrinDocenteLayout.createSequentialGroup()
                .addGroup(pnl2PrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2PrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnAulas.setBackground(new java.awt.Color(245, 245, 220));
        btnAulas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door1.png"))); // NOI18N
        btnAulas.setText("Salas");
        btnAulas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAulas.setContentAreaFilled(false);
        btnAulas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAulas.setIconTextGap(1);
        btnAulas.setOpaque(true);
        btnAulas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAulas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAulasActionPerformed(evt);
            }
        });

        lblPresioneOpcion.setBackground(new java.awt.Color(245, 245, 220));
        lblPresioneOpcion.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPresioneOpcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresioneOpcion.setText("PRESIONE UNA OPCIÓN: ");
        lblPresioneOpcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        lblPresioneOpcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPresioneOpcion.setOpaque(true);

        btnFamilias.setBackground(new java.awt.Color(245, 245, 220));
        btnFamilias.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnFamilias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tutores.jpg"))); // NOI18N
        btnFamilias.setText("Familias");
        btnFamilias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnFamilias.setContentAreaFilled(false);
        btnFamilias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFamilias.setIconTextGap(0);
        btnFamilias.setOpaque(true);
        btnFamilias.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFamilias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFamilias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliasActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(245, 245, 220));
        btnReportes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReportes.setContentAreaFilled(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setIconTextGap(0);
        btnReportes.setOpaque(true);
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrinDocenteLayout = new javax.swing.GroupLayout(pnlPrinDocente);
        pnlPrinDocente.setLayout(pnlPrinDocenteLayout);
        pnlPrinDocenteLayout.setHorizontalGroup(
            pnlPrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl2PrinDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrinDocenteLayout.createSequentialGroup()
                .addGroup(pnlPrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrinDocenteLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnFamilias, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addGroup(pnlPrinDocenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPresioneOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );
        pnlPrinDocenteLayout.setVerticalGroup(
            pnlPrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrinDocenteLayout.createSequentialGroup()
                .addComponent(pnl2PrinDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblPresioneOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlPrinDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAulas, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(btnFamilias, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrinDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrinDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea salir de KAS?", "Selecione una Opción", YES_NO_OPTION, QUESTION_MESSAGE);
        if (respuesta == 0) {
            this.dispose();
            inicioSesion is = new inicioSesion();
            is.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void pnlPrinDocenteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pnlPrinDocenteInputMethodTextChanged
    }//GEN-LAST:event_pnlPrinDocenteInputMethodTextChanged

    private void btnFamiliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliasActionPerformed
        abmFamilia abmF = new abmFamilia();
        abmF.interfazDocente(this);
        abmF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFamiliasActionPerformed

    private void btnAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAulasActionPerformed
        abmSala abmS = new abmSala();
        abmS.setVisible(true);
    }//GEN-LAST:event_btnAulasActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Reportes r = new Reportes();
        r.interfazDocente(this);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAulas;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFamilias;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblPresioneOpcion;
    private org.edisoncor.gui.panel.Panel pnl2PrinDocente;
    private org.edisoncor.gui.panel.Panel pnlPrinDocente;
    // End of variables declaration//GEN-END:variables
}
